server:
  port: 8080

spring:
  application:
    name: books-service
  datasource:
    url: @database.url@
    driverClassName: com.mysql.cj.jdbc.Driver
    username: service
    password: password
    hikari:
      connectionTimeout: 5000
      idleTimeout: 5000
      maxLifetime: 180000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

tracing:
  url:
    http://localhost:4317
