server:
  port: 8080

spring:
  datasource:
    url: @database.url@
    driverClassName: com.mysql.cj.jdbc.Driver
    username: service
    password: password
    hikari:
      connectionTimeout: 5000
      idleTimeout: 5000
      maxLifetime: 180000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
